import assert from 'node:assert/strict'
import test from 'node:test'
import { createExportDocument, supportedExportFormats } from './report-exports.js'

const report = {
  data: [
    {
      memberCode: 'MBR-001',
      member: 'Asha, "Mama"\nMrema',
      phone: '+255713000000',
      category: 'Family',
      pledged: 500000,
      paid: 200000,
      outstanding: 300000,
      effectiveDueDate: '2026-08-08',
      status: 'PARTIALLY_PAID',
      lastPayment: '2026-08-08T11:30:00.000Z',
    },
  ],
  summary: {
    pledgeCount: 1,
    totalPledged: 500000,
    totalPaid: 200000,
    totalOutstanding: 300000,
  },
}

const base = {
  eventName: 'Neema Wedding',
  filtersApplied: { status: 'ALL' },
  generatedAt: new Date('2026-08-08T12:00:00.000Z'),
  generatedBy: 'Fredrick Mrema',
  report,
  reportType: 'pledges' as const,
  tenantName: 'Ahadi Demo',
}

test('CSV export is UTF-8 and escapes commas, quotes and newlines', () => {
  const document = createExportDocument({ ...base, format: 'CSV' })
  assert.equal(document.contentType, 'text/csv; charset=utf-8')
  assert.equal(typeof document.body, 'string')
  const body = document.body as string
  assert.ok(body.startsWith('\uFEFF'))
  assert.match(body, /"Asha, ""Mama""\nMrema"/)
  assert.match(body, /500000/)
})

test('XLSX export produces an actual workbook package with numeric money cells', () => {
  const document = createExportDocument({ ...base, format: 'XLSX' })
  assert.equal(document.contentType, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
  assert.ok(Buffer.isBuffer(document.body))
  assert.equal(document.body.subarray(0, 2).toString('utf8'), 'PK')
  assert.match(document.body.toString('utf8'), /Pledged Amount \(TZS\)/)
  assert.match(document.body.toString('utf8'), /<v>500000<\/v>/)
})

test('PDF and print exports render report titles and Ahadi footer text', () => {
  const pdf = createExportDocument({ ...base, format: 'PDF' })
  const print = createExportDocument({ ...base, format: 'PRINT' })
  assert.ok(Buffer.isBuffer(pdf.body))
  assert.equal(pdf.body.subarray(0, 8).toString('utf8'), '%PDF-1.4')
  assert.match(pdf.body.toString('utf8'), /Pledge Report/)
  assert.equal(typeof print.body, 'string')
  const printBody = print.body as string
  assert.match(printBody, /window\.print/)
  assert.match(printBody, /This report was generated by Ahadi/)
})

test('supported export formats match batch 5 scope', () => {
  assert.deepEqual(supportedExportFormats('summary'), ['PDF', 'PRINT'])
  assert.deepEqual(supportedExportFormats('pledges'), ['CSV', 'XLSX', 'PDF', 'PRINT'])
  assert.deepEqual(supportedExportFormats('payment-methods'), ['XLSX', 'PDF', 'PRINT'])
  assert.deepEqual(supportedExportFormats('member-statement'), ['PDF', 'PRINT'])
})
